<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Shree" ignored="1" name="Test" tests="27" failures="1" timestamp="2020-04-23T07:17:27 IST" time="0.402" errors="0">
  <testcase name="accountCreate" time="0.016" classname="com.testngexample.Sample3"/>
  <testcase name="accountDelete" time="0.0" classname="com.testngexample.Sample3"/>
  <testcase name="accountEdit" time="0.0" classname="com.testngexample.Sample3"/>
  <testcase name="test1" time="0.0" classname="com.testngexample.Sample2"/>
  <testcase name="test2" time="0.0" classname="com.testngexample.Sample2"/>
  <testcase name="test3" time="0.016" classname="com.testngexample.Sample2"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.016" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="sendSMS" time="0.0" classname="com.testngexample.Sample5"/>
  <testcase name="c" time="0.0" classname="com.testngexample.Sample4"/>
  <testcase name="aab" time="0.0" classname="com.testngexample.Sample4"/>
  <testcase name="a" time="0.0" classname="com.testngexample.Sample4"/>
  <testcase name="test1" time="0.0" classname="com.testngexample.Sample7"/>
  <testcase name="test3" time="0.0" classname="com.testngexample.Sample7"/>
  <testcase name="test1" time="0.094" classname="com.testngexample.Sample6">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testngexample.Sample6.test1() didn&amp;apos;t finish within the time-out 5">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testngexample.Sample6.test1() didn't finish within the time-out 5
at java.lang.Thread.interrupt0(Native Method)
at java.lang.Thread.interrupt(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="com.testngexample.Sample8"/>
  <testcase name="createAccount" time="0.016" classname="com.testngexample.s4"/>
  <testcase name="editAccount" time="0.0" classname="com.testngexample.s4"/>
  <testcase name="deleteAccount" time="0.015" classname="com.testngexample.s4"/>
  <testcase name="test1" time="0.0" classname="com.testngexample.Sample"/>
  <testcase name="test2" time="0.0" classname="com.testngexample.Sample7">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
